### ISSUE TITLE
Make Give Feedback visible immediately

### ISSUE THREAD

**Issue by amieiro** [GlotPress/gp-translation-helpers#119]
## What problem does this address?
This was proposed by @la-geek [here](https://wordpress.slack.com/archives/C02RP4R9F/p1664543627980909). 

> Why do you always have to unfold Give Feedback first?
> This is very impractical, after a while it starts to get annoying.

## What is your proposed solution?
The proposed solution is to show the feedback form by default.

The current decision (hide the feedback form) was taken because we thought most of the actions will be taken without feedback. I would like to get feedback from GTE to maintain or to change this behavior.

**Comment by La-Geek** [comment]
> The current decision (hide the feedback form) was taken because we thought most of the actions will be taken without feedback

Who knows? It is a new feature. I think anyone who has opened this a few times in a row will agree, it just gets annoying. 
A default unfolded feedback form doesn't take up much space, and the fact that it's optional is clearly marked. But maybe it could additionally be called "Give Feedback (optional)" instead of "Give Feedback".

![show_feedback_form](https://user-images.githubusercontent.com/1585416/193599992-9582198e-0eca-474f-b4cd-f86047e895ca.jpg)

**Comment by amieiro** [comment]
[Discussion](https://wordpress.slack.com/archives/C02RP50LK/p1664953636708229) in the Polyglots weekly meeting.

**Comment by fxbenard** [comment]
Another point why not renaming it just to "Feedback", it's a feature not an action.

**Comment by La-Geek** [comment]
@fxbenard 
I am confused, sorry, I guess I don't understand you right.
Here you write 
> Another point why **not renaming** it just to "Feedback", 

and there:
> **Renaming from** Give feedback to Feedback #124

or did you simply post in the wrong thread?

**Comment by fxbenard** [comment]
@La-Geek Indeed I posted it here first and thought after it was better to open a new issue. Sorry about that, you can forget my comment here

**Comment by TRTCO** [comment]
Just "Feedback" is fine for me, too. But no matter how it is named, the feedback panel should be open for editors as default state. This encourages all of us to actually give feedback instead of just rejecting strings.
