### ISSUE TITLE
Add "Placeholder" as possible feedback reason when rejecting with feedback

### ISSUE THREAD

**Issue by NekoJonez** [GlotPress/gp-translation-helpers#128]
I think it would be useful to have "placeholder" as a standard reject reason. When translators give a bad suggestion with invalid placeholders.

I see it often with "%1$s"... Where translators see that S as part of the word to translate.

**Comment by trymebytes** [comment]
This is related to #72 , I think it would be interesting to allow validators define custom reasons.

**Comment by trymebytes** [comment]
I will go ahead to close this and reference it in #72 . Please feel free to reopen if this usecase here, is entirely different.
