### ISSUE TITLE
Restore `wporg-gp-customizations` behaviour for `<summary>` state

### ISSUE THREAD

**Issue by vlad-timotei** [GlotPress/gp-translation-helpers#141]
## What problem does this address?

In `wporg-gp-customizations` plugin, for each `<summary>` tag (such as Suggestions from Translation Memory & other languages) we have a listener that will store its current user decided state for the next render. With this in place, even if we have default open/closed states, the user can decide how they want it to be next time they see it.

[Source code here](https://github.com/WordPress/wordpress.org/blob/0a555bb6412daaf80c3def353985e05229fc4ca7/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/templates/js/editor.js#L284).

### What `gp-translation-helpers` changed?

https://github.com/GlotPress/gp-translation-helpers/blob/7a335df30a11d97a09e788e00094ac36ca78f8b3/js/reject-feedback.js#L24-L25

This affects the other summary elements and some users might want the ability to keep them closed or open.
So now the state is no longer preserved, as it used to be.
![Screenshot 2022-11-04 at 11 38 01](https://user-images.githubusercontent.com/65488419/199941264-f2bb9985-40a6-41b3-bcfd-19f3d9eb41b6.png)
(Suggestions from TM is open by default and Suggestions from other languages is closed by default)

## What is your proposed solution?

Unless there is a reason not to let the user decide if they want the summary tag open/closed, I'd propose to reverse [this commit](https://github.com/GlotPress/gp-translation-helpers/commit/3c4a9824736e01467fe3cc3ad1e8c0306ac0240a) that disables the wporg-gp-customizations listener on summary tags. 

@trymebytes I see the commit is named `Fix console error - remove click event added to <summary>`. Can you elaborate on that? Maybe we can find a fix without removing the listener.

If we don't want this feature to work for the feedback summary element, we can only specifically disable it for the feedback summary, not globally as we do now.

Of course, I fully support that the Feedback element (and other summary as well) to be opened by default (see #133) but I'd also like to keep the previous ability to save its state.

What do you think?

**Comment by trymebytes** [comment]
Thank you and I agree we that we should specifically disable it for the feedback summary, not globally.
