### ISSUE TITLE
Error 400 with addition of OpenAI translation

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/gp-translation-helpers#168]
After the implementation of OpenAI, I notice a 400 error for every translation added and saved
https://translate.wordpress.org/-save-external-suggestions 400
It seems that there is an access problem, I do not know where those suggestions are stored,
But I have the impression they are not stored currently

**Comment by amieiro** [comment]
Hi @psmits1567 

I can't reproduce this problem, so I think this problem has been solved. Can I close this issue? Thank you for your feedback.

**Comment by psmits1567** [comment]
@amieiro hi, double checked, I think it has been resolved. I do not see the errors anymore
