### ISSUE TITLE
New order for the other locales tab: {oc}” (change {ca,fr,it,es,gl}

### ISSUE THREAD

**Issue by MarcArmengou** [GlotPress/gp-translation-helpers#188]
Other locales tab for https://translate.wordpress.org/locale/oci/

```
'oc' => array( 'ca', 'fr', 'it', 'es', 'gl' ),
```

Thanks

**Comment by amieiro** [comment]
I need to change the Occitan slug form `oc` to `oci`.

From 

```
'oc' => array( 'ca', 'fr', 'it', 'es', 'gl' ),
```

to

```
'oci' => array( 'ca', 'fr', 'it', 'es', 'gl' ),
```

This is the result:

![image](https://github.com/GlotPress/gp-translation-helpers/assets/1667814/1c34344b-275b-4391-b874-999e42a86344)

**Comment by amieiro** [comment]
This update has been deployed at translate.w.org. You can take a look [here](https://translate.wordpress.org/projects/wp/6.1.x/admin/oci/default/?filters%5Bstatus%5D=current).
