### ISSUE TITLE
New order for the other locales tab: Uighur 

### ISSUE THREAD

**Issue by Nureli-Tashpolat** [GlotPress/gp-translation-helpers#201]
Please put in the top place these languages and locales for Uighur "Other Languages" and "Other locales" tab:

1. Turkish - tr_TR
2. Uzbek - uz_UZ
3. Azerbaijani - az
4. Chinese (China) - zh_CN
5. Chinese (Taiwan) - zh_TW

Nureli Tashpolat
Uighur Language GTE

@amieiro

**Comment by Nureli-Tashpolat** [comment]
Hi @amieiro,

Thank you for your quick response. Other locales is good, but I also need do same thing to Other languages section. And Other languages is more important and useful for translator.

Sorry for my lack explanation at first.  Can you please do that reorder to Other Languages section too, thank you!

Nureli

**Comment by amieiro** [comment]
Hi @Nureli-Tashpolat 

In both locations ("Other locales" and "Other languages"), the system shows the same information to the translator, but in the "Other locales" tab, the system order it with this "related languages" improvement. 

I hope in the future we will add this improvement to "Other languages". 

![image](https://github.com/GlotPress/gp-translation-helpers/assets/1667814/5ed3f54a-0a76-4d9c-aaac-fc878f427efc)

**Comment by Nureli-Tashpolat** [comment]
Thank you @amieiro, I got it.

I hope the improvement for other languages tab is not far away :). 

Should I need do to anything for push this to forward?

Nureli
