### ISSUE TITLE
Rejected translation doesn't appear in comment and there is no indicator for translation status shown in the comment

### ISSUE THREAD

**Issue by kharissulistiyo** [GlotPress/gp-translation-helpers#37]
I did testing the translation status updates on a single string. I got something like this in the History tab:

![Screen Shot 2022-03-06 at 16 09 03](https://user-images.githubusercontent.com/1859092/156917705-2ea451c2-cb39-4bc6-bc83-9c19f6877167.png)

I put comments in each status update. I got this issue: the rejected translation doesn’t appear in the comment, whilst other statuses do. See this screenshot:

![Discussion-Indonesia-Sydney-Free-GlotPress](https://user-images.githubusercontent.com/1859092/156917733-97bff26c-59af-46f2-9fda-2f1b9d798cfd.png)

Would it be possible to add color and text to indicate the translation status shown in the comment for clarity? For example:

![GlotPress-comment-adds-color-indicator](https://user-images.githubusercontent.com/1859092/156917747-1f2a32e6-32b5-42e3-a653-d34a5da2fea5.png)

**Comment by trymebytes** [comment]
Thanks for the feedback @kharissulistiyo! The rejected translation is shown in the footer of a comment only if that comment was posted as a feedback when rejecting the translation. If you added a comment on the discussion page for a rejected translation it won't be displayed.

Yes, the idea of adding a colour and status sounds good!

**Comment by amieiro** [comment]
This issue is being resolved in https://github.com/GlotPress/gp-translation-helpers/pull/104.

**Comment by trymebytes** [comment]
#104 which fixes this issue has been merged so I'm closing this.
