### ISSUE TITLE
With a waiting string you can select "Give feedback", but the feedback is not saved when set to "Fuzzy"  or "Approve"

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/gp-translation-helpers#39]
The discussion feature is for notifying the translator in case of an issue with the translation.
So if the PTE or GTE does decide not to accept this translation, the "Fuzzy" is mostly used to help the translator
So it is important that when a translation is set to "Fuzzy" the feedback should be saved.
Also it can be helpfull to save the feedback if you "Approve"  the translation.
So you can indicate to the translator to add more translations and ask to become PTE for the project
Tested this with @nao who had the same results and opinion

**Comment by fxbenard** [comment]
I second this.
In French community we put all strings who need to be fixed in fuzzy mode so the translators just have to fix and not start from zero when rejected.
As GTE feedback aren't saved so far

**Comment by lidialab** [comment]
I totally agree with Peter.
Also for: "Also it can be helpfull to save the feedback if you "Approve" the translation." because it may be helpful to leave a note on why a string is translated in a particular way in certain cases.

**Comment by akirk** [comment]
This was fixed in #92. Could you please confirm that this is working now? Thank you!

**Comment by amieiro** [comment]
This improvement was released in production a few weeks before. @psmits1567 can you confirm we can close this issue?

**Waiting strings**

![image](https://user-images.githubusercontent.com/1667814/193589459-fe44db11-3223-4258-a9b2-92920e3c74a6.png)

**Fuzzy string**

![image](https://user-images.githubusercontent.com/1667814/193589249-dafea9ae-f3fa-4951-8aad-c7357a5fbef7.png)

**Translated string**

![image](https://user-images.githubusercontent.com/1667814/193589347-add7bb12-37b9-410f-8466-3e263518c028.png)

**Comment by psmits1567** [comment]
Yes this one works on a desktop computer
