### ISSUE TITLE
IF a bulk reject is performed then the name of the person that did this is not set into the feedback

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/gp-translation-helpers#41]
When a bulk reject is performed with feedback, I would expect that the name of the person is set into the feedback
It is set to anonymous
![anonymous](https://user-images.githubusercontent.com/28138634/158825497-b818beda-802b-4bf3-9ac9-542de0f880e8.JPG)

**Comment by trymebytes** [comment]
@psmits1567 I am able to reproduce this and we are taking a look. Thanks!

**Comment by amieiro** [comment]
This [was resolved here](https://github.com/GlotPress/gp-translation-helpers/pull/49), so I am going to close this issue.
