### ISSUE TITLE
Double Loading of Discussions

### ISSUE THREAD

**Issue by akirk** [GlotPress/gp-translation-helpers#54]
In #40, we started to loading the discussions inline but I have noticed that while the discussion tab is indeed included already at page load, it unnecessarily gets loaded a second time. Also, the first time, links seem to be stripped (see in this screen recording and observe the **Logged in as** being modified after the AJAX has been loaded):
![double-request](https://user-images.githubusercontent.com/203408/162439635-2ec9de3a-09b1-4a16-acf0-6979ec6eec9d.gif)

Especially for larger installs we should avoid including the discussion data for load reasons.

**Comment by amieiro** [comment]
Related with this bug, when I load a discussion with a reply in the same thread, you can see that the replies are loaded correctly in the first time, but you can see a spinner preloading some content and, in a few seconds, the comments are reloaded with a wrong order. Take a look at the video to see it.

https://user-images.githubusercontent.com/1667814/164424256-8b076504-38c2-456c-9c2e-a59c759fdb77.mp4
