### ISSUE TITLE
No UI Feedback if Ajax Request fails

### ISSUE THREAD

**Issue by akirk** [GlotPress/gp-translation-helpers#68]
## Description

It has been reported to me by @La-Geek that the ajax-admin.php request failed with a server status 500. In that the UI just didn't do anything.
![image (1)](https://user-images.githubusercontent.com/203408/177499599-de3d69ac-ff3d-497a-8235-8f38c85fd644.png)

Actually, the request seem to have worked despite the 500 error, resulting in many duplicate comments:

![screenshot-translate wordpress org-2022 07 06-09_52_33](https://user-images.githubusercontent.com/203408/177499800-86db36c0-da97-4b91-a3b6-672746775337.png)

## Step-by-step reproduction instructions
Not reproducible because it eventually worked but a current string was rejected with a comment and reject reason "style."

## Expected behavior
The UI should not fail silently if the Ajax Request fails.

## Actual behavior
No response, it appears as if nothing happens after clicking the Reject button.

**Comment by akirk** [comment]
Notes for fixing this:
- We need better server-side logging for random admin-ajax.php 500 errors.
- The UI should show if an error happened and inform the user what to do (maybe check the discussions page if the comment acutally made it through?)

**Comment by amieiro** [comment]
Solved here https://github.com/GlotPress/gp-translation-helpers/pull/84.
