### ISSUE TITLE
More clarity needed on which discussion threads will be notified to project's authors

### ISSUE THREAD

**Issue by lidialab** [GlotPress/gp-translation-helpers#71]
## What problem does this address?
I think more clarity is needed **in the UI** on what discussions will be notified to the authors of the project.

## What is your proposed solution?
Add explanatory text in the dropdown menu, such as "(developers will be notified)".
So for example: "Typo in the English text (developers will be notified)".

**Comment by amieiro** [comment]
Solved here https://github.com/GlotPress/gp-translation-helpers/pull/88.

**Comment by akirk** [comment]
This has been merged and it now looks like this:

![image](https://user-images.githubusercontent.com/1667814/181496299-e591e5c5-da29-41ce-9ec8-41eaff298b50.png)
