### ISSUE TITLE
Custom Reasons

### ISSUE THREAD

**Issue by lidialab** [GlotPress/gp-translation-helpers#72]
## What problem does this address?
Will it be possible to add custom reasons in the future?

It can be very useful to customize them. For example in Italian we have a really huge amount of translations _fuzzied_ because of "Title Case" (when all words are capitalized).

**Comment by trymebytes** [comment]
Thank you for the feedback and yes I think it's a good idea to have custom reasons to cover for cases where none of the default reasons is applicable.

**Comment by trymebytes** [comment]
An issue with similar usecase was opened in #128 by @NekoJonez

**Comment by NekoJonez** [comment]
Honestly, I think it should work like this... A set of standard reasons that can be used locale wide and then a possible set of custom locale specific reasons. Or maybe even project specific reasons?

But I am only a bit worried UI wise. Since the more freedom you give a user, the more UI and Accessability things should be kept in mind.

**Comment by trymebytes** [comment]
Yes, I think we should explore these options. We can start by having the set of standard reasons we have right now, and then allow locale managers/GTEs add custom rejection reasons specific to their locales. Considering how this may impact the UI/UX, we may decide to limit the number of custom reasons that can be added too.

**Comment by lidialab** [comment]
Example of extra rejection motivations for all locales:
- Untranslated
- Incorrect date format (for this locale)
- Missing placeholder


Example of motivation for the Italian I am thinking of right now, just to reflect about it:
- Wrong capitalization
- Wrong accent
- Wrong spaces
- No "s" for English plurals in Italain
- Inconsistent translation of terms in this project 

(Yep, I guess that they should be more short... :) , it's only to think about it.)

Perhaps we can think to use a drop-down menu to include more reasons instead to limit the custom ones?

**Comment by trymebytes** [comment]
Yes  a drop-down might be more appropriate here, perhaps one that autosuggests as you type.
