### ISSUE TITLE
If a non PTE/GTE goes to a rejected line, there is no link to the comment record from the GTE

### ISSUE THREAD

**Issue by psmits1567** [GlotPress/gp-translation-helpers#76]
If a GTE bulk rejects translation, the translator gets an email with a link to the comment
But if the translator goes into the project and searches for rejected translations, he does not see a link to the comment
Also not if you go into the editor.
If a comment is present on a rejected translation and a comment is present, I would like to see the link to the comment

**Comment by akirk** [comment]
This is not easy to implement for performance reasons, we are trying to solve this with #65.

**Comment by amieiro** [comment]
@psmits1567 I think this was resolved with the new status: changed requested, because you can filter the strings with feedback and which need to update something in the translation. Is it ok to close this issue?

**Comment by psmits1567** [comment]
Yes you can close it
